/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgenticRouteImport } from './routes/agentic'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as EndpointRouteImport } from './routes/endpoint'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as ScheduledRouteImport } from './routes/scheduled'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as CChatIdRouteImport } from './routes/c.$chatId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenticRoute = AgenticRouteImport.update({
  id: '/agentic',
  path: '/agentic',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const EndpointRoute = EndpointRouteImport.update({
  id: '/endpoint',
  path: '/endpoint',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduledRoute = ScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const CChatIdRoute = CChatIdRouteImport.update({
  id: '/c/$chatId',
  path: '/c/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agentic': typeof AgenticRoute
  '/company': typeof CompanyRoute
  '/connect': typeof ConnectRoute
  '/connectors': typeof ConnectorsRoute
  '/endpoint': typeof EndpointRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/plugins': typeof PluginsRoute
  '/projects': typeof ProjectsRoute
  '/providers': typeof ProvidersRoute
  '/scheduled': typeof ScheduledRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/tasks': typeof TasksRoute
  '/c/$chatId': typeof CChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agentic': typeof AgenticRoute
  '/company': typeof CompanyRoute
  '/connect': typeof ConnectRoute
  '/connectors': typeof ConnectorsRoute
  '/endpoint': typeof EndpointRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/plugins': typeof PluginsRoute
  '/projects': typeof ProjectsRoute
  '/providers': typeof ProvidersRoute
  '/scheduled': typeof ScheduledRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/tasks': typeof TasksRoute
  '/c/$chatId': typeof CChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agentic': typeof AgenticRoute
  '/company': typeof CompanyRoute
  '/connect': typeof ConnectRoute
  '/connectors': typeof ConnectorsRoute
  '/endpoint': typeof EndpointRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/plugins': typeof PluginsRoute
  '/projects': typeof ProjectsRoute
  '/providers': typeof ProvidersRoute
  '/scheduled': typeof ScheduledRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/tasks': typeof TasksRoute
  '/c/$chatId': typeof CChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agentic'
    | '/company'
    | '/connect'
    | '/connectors'
    | '/endpoint'
    | '/library'
    | '/onboarding'
    | '/plugins'
    | '/projects'
    | '/providers'
    | '/scheduled'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/c/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agentic'
    | '/company'
    | '/connect'
    | '/connectors'
    | '/endpoint'
    | '/library'
    | '/onboarding'
    | '/plugins'
    | '/projects'
    | '/providers'
    | '/scheduled'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/c/$chatId'
  id:
    | '__root__'
    | '/'
    | '/agentic'
    | '/company'
    | '/connect'
    | '/connectors'
    | '/endpoint'
    | '/library'
    | '/onboarding'
    | '/plugins'
    | '/projects'
    | '/providers'
    | '/scheduled'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/c/$chatId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenticRoute: typeof AgenticRoute
  CompanyRoute: typeof CompanyRoute
  ConnectRoute: typeof ConnectRoute
  ConnectorsRoute: typeof ConnectorsRoute
  EndpointRoute: typeof EndpointRoute
  LibraryRoute: typeof LibraryRoute
  OnboardingRoute: typeof OnboardingRoute
  PluginsRoute: typeof PluginsRoute
  ProjectsRoute: typeof ProjectsRoute
  ProvidersRoute: typeof ProvidersRoute
  ScheduledRoute: typeof ScheduledRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  TasksRoute: typeof TasksRoute
  CChatIdRoute: typeof CChatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentic': {
      id: '/agentic'
      path: '/agentic'
      fullPath: '/agentic'
      preLoaderRoute: typeof AgenticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endpoint': {
      id: '/endpoint'
      path: '/endpoint'
      fullPath: '/endpoint'
      preLoaderRoute: typeof EndpointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduled': {
      id: '/scheduled'
      path: '/scheduled'
      fullPath: '/scheduled'
      preLoaderRoute: typeof ScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$chatId': {
      id: '/c/$chatId'
      path: '/c/$chatId'
      fullPath: '/c/$chatId'
      preLoaderRoute: typeof CChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenticRoute: AgenticRoute,
  CompanyRoute: CompanyRoute,
  ConnectRoute: ConnectRoute,
  ConnectorsRoute: ConnectorsRoute,
  EndpointRoute: EndpointRoute,
  LibraryRoute: LibraryRoute,
  OnboardingRoute: OnboardingRoute,
  PluginsRoute: PluginsRoute,
  ProjectsRoute: ProjectsRoute,
  ProvidersRoute: ProvidersRoute,
  ScheduledRoute: ScheduledRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  TasksRoute: TasksRoute,
  CChatIdRoute: CChatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
